/**
 * Creates the forum's content types and seeds a board.
 *
 * Topics are this app's own content type. Replies and votes are the two types
 * the schema plugin's comments preset creates, `comments` and `comment_votes`,
 * and every one of them is written through the same admin content route as a
 * topic.
 *
 * Safe to run more than once. Applying an existing schema is accepted, a
 * preset whose types already exist answers 409 and is taken as done, and
 * seeding stops if the forum already has topics.
 */
import {
	LyeveError,
	applySchemas,
	createContent,
	listContent,
	lyeveFromEnv
} from '../src/lib/lyeve/index.ts';

const client = lyeveFromEnv();

const TOPICS = 'forum_topics';

await applySchemas(client, [
	{
		name: TOPICS,
		display_name: 'Forum topics',
		fields: [
			{ name: 'title', field_type: 'text', required: true },
			{ name: 'slug', field_type: 'text', required: true, indexed: true },
			{ name: 'body', field_type: 'text' },
			{ name: 'category', field_type: 'text', indexed: true },
			{ name: 'author_name', field_type: 'text' },
			{ name: 'pinned', field_type: 'boolean' },
			{ name: 'locked', field_type: 'boolean' }
		]
	}
]);
console.log('content type ready');

// The preset refuses, creating nothing, when any type it would create already
// exists. On a second run that is the expected answer, not a failure.
try {
	await client.request('admin', '/api/admin/schemas/presets/comments', { method: 'POST' });
	console.log('comments preset applied: comments, comment_votes');
} catch (err) {
	if (!(err instanceof LyeveError) || err.status !== 409) throw err;
	console.log('comments preset already applied');
}

if ((await listContent(client, TOPICS, { limit: 25 })).length > 0) {
	console.log('topics already seeded, nothing to do');
	process.exit(0);
}

/**
 * Voters are invented here.
 *
 * A vote record carries a free-text voter key, so these ids stand in for
 * readers who have no account. Fixed rather than random, so the vote slugs a
 * repeat run would write collide with the first run's instead of stacking.
 */
const VOTERS = [
	'6b9d4f2a-7c31-4a0e-9f18-2d5c8e1b47a3',
	'0c47e9b1-5a82-4d63-8e0f-7b1a93c25d64',
	'd21f8a63-4e07-4c95-b8d1-3f6a05e79c12'
];

interface SeedReply {
	author: string;
	email: string;
	body: string;
	/** Left out means approved. Pending replies are what the queue page shows. */
	pending?: boolean;
	/** How many of the seeded voters find this reply useful. */
	upvotes?: number;
	children?: SeedReply[];
}

interface SeedTopic {
	slug: string;
	title: string;
	category: string;
	author: string;
	body: string;
	pinned?: boolean;
	locked?: boolean;
	replies: SeedReply[];
}

const topics: SeedTopic[] = [
	{
		slug: 'forum-lanternfish-3-2-thumbnails',
		title: 'Lanternfish 3.2 puts thumbnail work on a queue',
		category: 'announcements',
		author: 'Margit Sandoval',
		pinned: true,
		body: '3.2 is out. The change everyone will notice is that thumbnails are generated by a queue with a fixed number of workers instead of one goroutine per new file.\n\nOn the machine we test against, importing four thousand raw files used to take the box out of service for the duration. It now finishes in roughly the same wall time and leaves enough headroom to browse the library while it works.\n\nUpgrading is the usual two steps. Stop the service, run the migration, start it again. The thumbnail cache is not invalidated, so nothing is regenerated unless you ask for it.',
		replies: [
			{
				author: 'Aisha Bello',
				email: 'aisha@example.net',
				body: 'The queue depth is configurable, I hope? Four workers is generous on a two core machine.'
			},
			{
				author: 'Margit Sandoval',
				email: 'margit@example.org',
				body: 'It is, and it defaults to the number of cores rather than four. Set `thumbnail_workers` if you want to hold some back.',
				upvotes: 2
			},
			{
				author: 'Dilan Ferreira',
				email: 'dilan@example.net',
				body: 'Is the container image tagged for this yet, or is it source only for now?',
				pending: true
			}
		]
	},
	{
		slug: 'forum-import-stalls-at-40-percent',
		title: 'Import stalls at 40 percent on a 400,000 photo library',
		category: 'help',
		author: 'Priya Raghunathan',
		body: 'I am moving a library of about four hundred thousand photos off an old NAS. The import runs happily for twenty minutes and then stops at roughly 40 percent every time. No error in the interface, no crash, and the process is still alive and using no CPU.\n\nIt is reproducible: same percentage, same wall clock, three runs in a row. Restarting the import picks up where it left off and then stops again a few thousand files later.',
		replies: [
			{
				author: 'Tomas Lindqvist',
				email: 'tomas@example.se',
				body: 'Run it again with `--verbose` and paste the last few lines before it goes quiet. A stall with no CPU is usually something waiting rather than something looping.',
				children: [
					{
						author: 'Priya Raghunathan',
						email: 'priya@example.com',
						body: 'Here is the tail of it:\n\n```\nimport: scanned 163402 files\nimport: sidecar queue depth 8192\nimport: waiting for sidecar writer\n```\n\nAnd then nothing for as long as I leave it.',
						children: [
							{
								author: 'Tomas Lindqvist',
								email: 'tomas@example.se',
								body: 'That is the sidecar writer, and 8192 is the queue ceiling. The writer is blocked on the NAS, so the queue fills and the scanner stops.\n\nThe fix is to write sidecars locally and sync them afterwards. **Point `sidecar_path` at local disk** and the import runs to the end. There is a note about it in [the storage guide](https://example.org/lanternfish/storage).',
								upvotes: 3
							}
						]
					}
				]
			},
			{
				author: 'Dilan Ferreira',
				email: 'dilan@example.net',
				body: 'Seeing the same thing on 3.1.4 with an SMB mount. Will try the local sidecar path tonight and report back.',
				pending: true
			}
		]
	},
	{
		slug: 'forum-two-years-on-a-fanless-mini-pc',
		title: 'Two years of this on a fanless mini PC',
		category: 'showcase',
		author: 'Aisha Bello',
		body: 'Someone asked in another thread what the smallest sensible machine for this is, so here is two years of data.\n\nThe box is a fanless four core mini PC with 16GB of memory and a single 4TB SSD, sitting on a shelf in a cupboard. It holds 210,000 photos and about 900 hours of video. Nothing has been replaced.\n\nThe only thing I would do differently is put the database on its own partition. Not for performance, but so that a full disk does not take both down at once.',
		replies: [
			{
				author: 'Nathan Choi',
				email: 'nathan@example.com',
				body: 'How long does a full reindex take on that? I have a similar machine and I have been putting it off.'
			},
			{
				author: 'Aisha Bello',
				email: 'aisha@example.net',
				body: 'About five hours for the whole library with `--rebuild-thumbnails`, and forty minutes without. I start it before bed.',
				upvotes: 1
			}
		]
	},
	{
		slug: 'forum-exif-dates-off-by-one-hour',
		title: 'EXIF dates off by one hour after the clocks changed',
		category: 'help',
		author: 'Nathan Choi',
		locked: true,
		body: 'Every photo taken before the clocks went back is showing an hour later than it was taken. The files are unchanged: exiftool reads the original time correctly.\n\nThis is only in the timeline view. The file details panel shows the right time.',
		replies: [
			{
				author: 'Margit Sandoval',
				email: 'margit@example.org',
				body: 'The timeline groups by local day using the current offset rather than the offset that was in effect when the photo was taken. That is a bug and it is ours.'
			},
			{
				author: 'Margit Sandoval',
				email: 'margit@example.org',
				body: 'Fixed in 3.2.1. The timeline now stores the offset with the timestamp instead of deriving it at read time. Closing this one.',
				upvotes: 2
			}
		]
	},
	{
		slug: 'forum-what-do-you-photograph-when-testing',
		title: 'What do you photograph when you are testing?',
		category: 'off-topic',
		author: 'Tomas Lindqvist',
		body: 'I have four hundred nearly identical photographs of the same kitchen chair, taken over three years, because it is the only thing that is always in the same place when I need a test file.\n\nWhat is everyone else using?',
		replies: [
			{
				author: 'Priya Raghunathan',
				email: 'priya@example.com',
				body: 'A cat who is deeply tired of being a test fixture.',
				upvotes: 2
			},
			{
				author: 'Dilan Ferreira',
				email: 'dilan@example.net',
				body: 'The view out of the office window, once an hour, for a year. It turned out to be a decent test of the timeline view.',
				pending: true
			}
		]
	}
];

interface CommentInput {
	topicId: string;
	body: string;
	author_name: string;
	author_email: string;
	status: 'pending' | 'approved';
	parent?: string;
}

/**
 * Creates one reply. A seeded board needs approved replies to read as a board,
 * so the seed chooses the status. A visitor's reply is always written pending.
 */
async function createComment(input: CommentInput): Promise<string> {
	const created = await createContent(client, {
		schema: 'comments',
		slug: `forum-reply-${crypto.randomUUID()}`,
		title: `Reply to ${input.topicId}`,
		body: {
			target_schema: TOPICS,
			target_id: input.topicId,
			parent: input.parent,
			author_name: input.author_name,
			author_email: input.author_email,
			body: input.body,
			status: input.status
		}
	});
	return created.id;
}

async function seedReplies(topicId: string, replies: SeedReply[], parent?: string) {
	for (const reply of replies) {
		const id = await createComment({
			topicId,
			parent,
			author_name: reply.author,
			author_email: reply.email,
			body: reply.body,
			status: reply.pending ? 'pending' : 'approved'
		});

		for (const voter of VOTERS.slice(0, reply.upvotes ?? 0)) {
			await createContent(client, {
				schema: 'comment_votes',
				slug: `forum-vote-${id}-${voter}`,
				title: 'Forum vote',
				body: { comment: id, voter_key: voter, value: 1 }
			});
		}

		if (reply.children) await seedReplies(topicId, reply.children, id);
	}
}

let replyCount = 0;
let pendingCount = 0;

for (const topic of topics) {
	const { id } = await createContent(client, {
		schema: TOPICS,
		slug: topic.slug,
		title: topic.title,
		body: {
			slug: topic.slug,
			body: topic.body,
			category: topic.category,
			author_name: topic.author,
			pinned: topic.pinned ?? false,
			locked: topic.locked ?? false
		}
	});

	// A reply names the topic by entry id rather than slug, so renaming a topic
	// cannot orphan its replies. Nothing enforces the link: target_id is a
	// text column with no foreign key.
	await seedReplies(id, topic.replies);

	const count = (function total(replies: SeedReply[]): number {
		return replies.reduce((n, reply) => {
			if (reply.pending) pendingCount++;
			return n + 1 + total(reply.children ?? []);
		}, 0);
	})(topic.replies);
	replyCount += count;
}

console.log(
	`seeded ${topics.length} topics and ${replyCount} replies, ${pendingCount} of them waiting for a moderator`
);
